In [12]:
import pandas as pd
df = pd.read_csv('18.csv')
df.head()

,id,creationdate,score,viewcount,title,answercount,commentcount,favoritecount,quest_name,quest_rep,ans_name,ans_rep
0,332289,2008-12-01 21:24:44,3184,5962784,How do I change the size of figures drawn with...,14,1,0.0,tatwright,37837.0,NaN,NaN
1,2051744,2010-01-12 19:31:47,420,587728,How to invert the x or y axis,10,3,0.0,DarkAnt,4211.0,Demitri,13369.0
2,2225995,2010-02-09 00:51:38,51,59922,How can I create stacked line graph?,4,0,0.0,David Underhill,15936.0,doug,69290.0
3,5486226,2011-03-30 12:26:50,7,6393,Rolling median in python,5,4,0.0,yueerhu,175.0,Mike Pennington,42288.0
4,5515021,2011-04-01 14:50:44,10,13744,Compute a compounded return series in Python,3,6,0.0,Jason Strimpel,14916.0,Mike Pennington,42288.0

In [18]:
import pandas as pd

df = pd.read_csv('18.csv')

df['creationdate'] = pd.to_datetime(df['creationdate'])

questions_before_2014 = df[df['creationdate'] < '2014-01-01']
print(" 2014-yildan oldin yaratilgan savollar:\n", questions_before_2014)

high_score_questions = df[df['score'] > 50]
print("\n Skori 50 dan katta savollar:\n", high_score_questions)

medium_score_questions = df[(df['score'] >= 50) & (df['score'] <= 100)]
print("\n Skori 50 va 100 orasida bo‘lgan savollar:\n", medium_score_questions)

scott_questions = df[df['ans_name'] == 'Scott Boston']
print("\n Scott Boston javob bergan savollar:\n", scott_questions)

users = ['User1', 'User2', 'User3', 'User4', 'User5']
questions_by_users = df[df['ans_name'].isin(users)]
print("\n Ushbu 5 foydalanuvchi javob bergan savollar:\n", questions_by_users)

unutbu_questions = df[
    (df['creationdate'] >= '2014-03-01') &
    (df['creationdate'] <= '2014-10-31') &
    (df['ans_name'] == 'Unutbu') &
    (df['score'] < 5)
]
print("\n Unutbu javob bergan va 2014 mart-oktabr oralig‘ida yaratilgan, skori <5 bo‘lgan savollar:\n", unutbu_questions)

filtered_questions = df[(df['score'].between(5, 10)) | (df['viewcount'] > 10000)]
print("\n Skori 5-10 oralig‘ida yoki ko‘rish soni 10,000 dan katta savollar:\n", filtered_questions)

not_scott_questions = df[df['ans_name'] != 'Scott Boston']
print("\n Scott Boston javob bermagan savollar:\n", not_scott_questions)

 2014-yildan oldin yaratilgan savollar:
         id        creationdate  score  viewcount  \
0   332289 2008-12-01 21:24:44   3184    5962784
1  2051744 2010-01-12 19:31:47    420     587728
2  2225995 2010-02-09 00:51:38     51      59922
3  5486226 2011-03-30 12:26:50      7       6393
4  5515021 2011-04-01 14:50:44     10      13744

                                               title  answercount  \
0  How do I change the size of figures drawn with...           14
1                      How to invert the x or y axis           10
2               How can I create stacked line graph?            4
3                           Rolling median in python            5
4       Compute a compounded return series in Python            3

   commentcount  favoritecount       quest_name  quest_rep         ans_name  \
0             1            0.0        tatwright    37837.0              NaN
1             3            0.0          DarkAnt     4211.0          Demitri
2             0            0.0  David Underhill    15936.0             doug
3             4            0.0          yueerhu      175.0  Mike Pennington
4             6            0.0   Jason Strimpel    14916.0  Mike Pennington

   ans_rep
0      NaN
1  13369.0
2  69290.0
3  42288.0
4  42288.0

 Skori 50 dan katta savollar:
         id        creationdate  score  viewcount  \
0   332289 2008-12-01 21:24:44   3184    5962784
1  2051744 2010-01-12 19:31:47    420     587728
2  2225995 2010-02-09 00:51:38     51      59922

                                               title  answercount  \
0  How do I change the size of figures drawn with...           14
1                      How to invert the x or y axis           10
2               How can I create stacked line graph?            4

   commentcount  favoritecount       quest_name  quest_rep ans_name  ans_rep
0             1            0.0        tatwright    37837.0      NaN      NaN
1             3            0.0          DarkAnt     4211.0  Demitri  13369.0
2             0            0.0  David Underhill    15936.0     doug  69290.0

 Skori 50 va 100 orasida bo‘lgan savollar:
         id        creationdate  score  viewcount  \
2  2225995 2010-02-09 00:51:38     51      59922

                                  title  answercount  commentcount  \
2  How can I create stacked line graph?            4             0

   favoritecount       quest_name  quest_rep ans_name  ans_rep
2            0.0  David Underhill    15936.0     doug  69290.0

 Scott Boston javob bergan savollar:
 Empty DataFrame
Columns: [id, creationdate, score, viewcount, title, answercount, commentcount, favoritecount, quest_name, quest_rep, ans_name, ans_rep]
Index: []

 Ushbu 5 foydalanuvchi javob bergan savollar:
 Empty DataFrame
Columns: [id, creationdate, score, viewcount, title, answercount, commentcount, favoritecount, quest_name, quest_rep, ans_name, ans_rep]
Index: []

 Unutbu javob bergan va 2014 mart-oktabr oralig‘ida yaratilgan, skori <5 bo‘lgan savollar:
 Empty DataFrame
Columns: [id, creationdate, score, viewcount, title, answercount, commentcount, favoritecount, quest_name, quest_rep, ans_name, ans_rep]
Index: []

 Skori 5-10 oralig‘ida yoki ko‘rish soni 10,000 dan katta savollar:
         id        creationdate  score  viewcount  \
0   332289 2008-12-01 21:24:44   3184    5962784
1  2051744 2010-01-12 19:31:47    420     587728
2  2225995 2010-02-09 00:51:38     51      59922
3  5486226 2011-03-30 12:26:50      7       6393
4  5515021 2011-04-01 14:50:44     10      13744

                                               title  answercount  \
0  How do I change the size of figures drawn with...           14
1                      How to invert the x or y axis           10
2               How can I create stacked line graph?            4
3                           Rolling median in python            5
4       Compute a compounded return series in Python            3

   commentcount  favoritecount       quest_name  quest_rep         ans_name  \
0             1            0.0        tatwright    37837.0              NaN
1             3            0.0          DarkAnt     4211.0          Demitri
2             0            0.0  David Underhill    15936.0             doug
3             4            0.0          yueerhu      175.0  Mike Pennington
4             6            0.0   Jason Strimpel    14916.0  Mike Pennington

   ans_rep
0      NaN
1  13369.0
2  69290.0
3  42288.0
4  42288.0

 Scott Boston javob bermagan savollar:
         id        creationdate  score  viewcount  \
0   332289 2008-12-01 21:24:44   3184    5962784
1  2051744 2010-01-12 19:31:47    420     587728
2  2225995 2010-02-09 00:51:38     51      59922
3  5486226 2011-03-30 12:26:50      7       6393
4  5515021 2011-04-01 14:50:44     10      13744

                                               title  answercount  \
0  How do I change the size of figures drawn with...           14
1                      How to invert the x or y axis           10
2               How can I create stacked line graph?            4
3                           Rolling median in python            5
4       Compute a compounded return series in Python            3

   commentcount  favoritecount       quest_name  quest_rep         ans_name  \
0             1            0.0        tatwright    37837.0              NaN
1             3            0.0          DarkAnt     4211.0          Demitri
2             0            0.0  David Underhill    15936.0             doug
3             4            0.0          yueerhu      175.0  Mike Pennington
4             6            0.0   Jason Strimpel    14916.0  Mike Pennington

   ans_rep
0      NaN
1  13369.0
2  69290.0
3  42288.0
4  42288.0